### ISSUE TITLE
error while listining to ports 

### ISSUE THREAD

**Issue by MR-pentestGuy** [boku7/StockManagement-XSS-Login-CredHarvester#1]
Traceback (most recent call last):
  File "StockMng-XSS-LoginCredHarvester.py", line 109, in <module>
    s.bind((LHOST,LPORT))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

**Comment by boku7** [comment]
Sounds like you need to enter your IP address correctly and make sure there is nothing already bound to the port

**Comment by sri-sanath** [comment]
So it would be like url my ip and some port or the port 80 
Url ip 80 
Should I use netcat to listen if not port 80

**Comment by boku7** [comment]
Sri, are you also mrbatman / mrpentestguy? Are you trolling me, i've looked at your other recent issues history.

**Comment by boku7** [comment]
I have no clue what your trying to do. The script should work as is, by just replacing the CLI arguments from the example with your own. This one is also built using python 2.7. Using >2.7 will result in errors.
I will not be providing any additional support for this, as it is a proof of concept exploit code for a vulnerability.
There is no issue with the exploit code to do it's primary function - exploiting the vulnerability.
You will have to reach out to others, maybe stackexchange.com to debug the python, golang, and other runtime issues you experience due to your specific environment.

**Comment by sri-sanath** [comment]
No no bro I am not trolling you I am really sorry about that I kind get notifications on both the account I would like to apologise for that
